# Generated by Django 4.1 on 2022-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новость',
                'ordering': ['-id'],
            },
        ),
    ]
